# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to NPM

on:
  release:
    types: [published]
  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/

      - name: Ensure npm >= 11.5.1
        run: npm install -g npm@latest

      - run: npm ci

      - run: npm run build

      - run: npm publish
